### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by katasuno** [Litzuck/lol-spectator-overlay-client#1]
(node:12168) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

When I run it I get this error. What is the solution?

**Comment by Litzuck** [comment]
This line shouldn't impact the functionality of the application, because it is just a warning, which can be ignored. However there were some errors in the last release, which have been fixed now in the release [v1.0.1](https://github.com/Litzuck/lol-spectator-overlay-client/releases/tag/v1.0.1)
I think your problem should be fixed with this release. If not let me know.

**Comment by katasuno** [comment]
But the selected character does not appear and the duration does not change.
![image](https://user-images.githubusercontent.com/62215083/109431503-0664b880-7a18-11eb-9642-c1aa1d406edb.png)

**Comment by katasuno** [comment]
Great worked!
