### ISSUE TITLE
Champ image is too zoomed

### ISSUE THREAD

**Issue by sod101316** [Litzuck/lol-spectator-overlay-client#32]
![image](https://user-images.githubusercontent.com/59684822/170945822-2d35d472-9106-4a48-bfa1-9d27229a7520.png)
How can i fix it?

**Comment by Litzuck** [comment]
Thanks, for pointing this out. There seems to be a bug in the build version of release 2.2.1, which is fixed by 2.2.2.
Furthemore you have to delete the following folder `%APPDATA%/lol-esports-spectate-client/images` and re-download the images through the app. After that everything should work fine.
